(** This file has been generated by the Catala compiler, do not edit! *)

open Runtime_ocaml.Runtime
open Runtime_jsoo.Runtime
open Js_of_ocaml
open Moyenne

[@@@ocaml.warning "-4-26-27-32-41-42"]

(* Generated API *)

class type moyenne =
  object method moy: Js.number Js.t Js.readonly_prop
  end
  let moyenne_to_js (moyenne : Moyenne.t) : moyenne Js.t =
    object%js
      val moy = Js.number_of_float @@ decimal_to_float moyenne.moy
      end
  let moyenne_of_js (moyenne : moyenne Js.t) : Moyenne.t =
    {moy = decimal_of_float @@ Js.float_of_number moyenne##.moy
    }

class type moyenne_in =
  object method notesIn: int Js.js_array Js.t Js.readonly_prop
  end
  let moyenne_in_to_js (moyenne_in : Moyenne_in.t) : moyenne_in Js.t =
    object%js
      val notesIn =
        Js.array @@ Array.map (fun x -> integer_to_int x) moyenne_in.notes_in
      end
  let moyenne_in_of_js (moyenne_in : moyenne_in Js.t) : Moyenne_in.t =
    {
      notes_in =
        Array.map (fun x -> integer_of_int x) @@ Js.to_array
          moyenne_in##.notesIn
    }




let moyenne (moyenne_in : moyenne_in Js.t)
  : moyenne Js.t =
  execute_or_throw_error
    (fun () -> moyenne_in |> moyenne_in_of_js |> moyenne |> moyenne_to_js)


let () =
   Js.export "MoyenneLib"
    (object%js
      
      method moyenne : (moyenne_in Js.t -> moyenne Js.t) Js.callback =
        Js.wrap_callback moyenne
      
    end)