(** This file has been generated by the Catala compiler, do not edit! *)

(* open Runtime_ocaml.Runtime
open Runtime_jsoo.Runtime *)
open Js_of_ocaml
open Moyenne_test

[@@@ocaml.warning "-4-26-27-32-41-42"]

(* Generated API *)

class type moyenne =
  object method moy: Js.number Js.t Js.readonly_prop
  end
  let moyenne_to_js (moyenne : Moyenne.t) : moyenne Js.t =
    object%js
      val moy = Js.number_of_float @@ decimal_to_float moyenne.moy
      end
  let moyenne_of_js (moyenne : moyenne Js.t) : Moyenne.t =
    {moy = decimal_of_float @@ Js.float_of_number moyenne##.moy
    }

class type moyenne_in =
object end
let moyenne_in_to_js (_ : Moyenne_in.t) : moyenne_in Js.t = object%js end
let moyenne_in_of_js (_ : moyenne_in Js.t) : Moyenne_in.t = ()



let moyenne (moyenne_in : moyenne_in Js.t)
  : moyenne Js.t =
  execute_or_throw_error
    (fun () -> moyenne_in |> moyenne_in_of_js |> moyenne |> moyenne_to_js)


let () =
   Js.export "MoyenneTestLib"
    (object%js
      
      method moyenne : (moyenne_in Js.t -> moyenne Js.t) Js.callback =
        Js.wrap_callback moyenne
      
    end)